/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ComercialRouteImport } from './routes/comercial'
import { Route as ComunicacaoRouteImport } from './routes/comunicacao'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as ProcessosRouteImport } from './routes/processos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialRoute = ComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunicacaoRoute = ComunicacaoRouteImport.update({
  id: '/comunicacao',
  path: '/comunicacao',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessosRoute = ProcessosRouteImport.update({
  id: '/processos',
  path: '/processos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/clientes': typeof ClientesRoute
  '/comercial': typeof ComercialRoute
  '/comunicacao': typeof ComunicacaoRoute
  '/financeiro': typeof FinanceiroRoute
  '/processos': typeof ProcessosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/clientes': typeof ClientesRoute
  '/comercial': typeof ComercialRoute
  '/comunicacao': typeof ComunicacaoRoute
  '/financeiro': typeof FinanceiroRoute
  '/processos': typeof ProcessosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/clientes': typeof ClientesRoute
  '/comercial': typeof ComercialRoute
  '/comunicacao': typeof ComunicacaoRoute
  '/financeiro': typeof FinanceiroRoute
  '/processos': typeof ProcessosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/clientes'
    | '/comercial'
    | '/comunicacao'
    | '/financeiro'
    | '/processos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/clientes'
    | '/comercial'
    | '/comunicacao'
    | '/financeiro'
    | '/processos'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/clientes'
    | '/comercial'
    | '/comunicacao'
    | '/financeiro'
    | '/processos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  ClientesRoute: typeof ClientesRoute
  ComercialRoute: typeof ComercialRoute
  ComunicacaoRoute: typeof ComunicacaoRoute
  FinanceiroRoute: typeof FinanceiroRoute
  ProcessosRoute: typeof ProcessosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial': {
      id: '/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof ComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicacao': {
      id: '/comunicacao'
      path: '/comunicacao'
      fullPath: '/comunicacao'
      preLoaderRoute: typeof ComunicacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processos': {
      id: '/processos'
      path: '/processos'
      fullPath: '/processos'
      preLoaderRoute: typeof ProcessosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  ClientesRoute: ClientesRoute,
  ComercialRoute: ComercialRoute,
  ComunicacaoRoute: ComunicacaoRoute,
  FinanceiroRoute: FinanceiroRoute,
  ProcessosRoute: ProcessosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
